### ISSUE TITLE
SIGABRT: value cannot be negative. Parameter name: value in MathEx+UFraction32.FromDouble (System.Double value)

### ISSUE THREAD

**Issue by MAX-POLKOVNIK** [samafshari/RedCorners.ExifLibrary#1]
I got following exception:

`MathEx+UFraction32.FromDouble (System.Double value)
RedCorners.ExifLibrary.MathEx+UFraction32..ctor (System.Double value) <0x104145680 + 0x00037> in <9fc0602bba8246069acc6ee5bf1a4103#26b46d6ca3448a7da21fb7e42213a79f>:0
RedCorners.ExifLibrary.MathEx+UFraction32..ctor (System.Single value) <0x104145630 + 0x00037> in <9fc0602bba8246069acc6ee5bf1a4103#26b46d6ca3448a7da21fb7e42213a79f>:0
ExifPropertyCollection.Set (RedCorners.ExifLibrary.ExifTag key, System.Single d, System.Single m, System.Single s)
GPSExtensions.SetGPSCoords (RedCorners.ExifLibrary.ImageFile file, System.Single latitude, System.Single longitude)`

Used coordinates 32.79123, -96.79033
Used latest Xamarin.Android & Xamarin.iOS

**Comment by MAX-POLKOVNIK** [comment]
If I use positive coordinates (latitude > 0 and longitude > 0) no crash happens

**Comment by MAX-POLKOVNIK** [comment]
Hmm... It's something strange. I dive into library and check GetGPSCoords/SetGPSCoords.
They absolutely ignores GPSLatitudeRef and GPSLongitudeRef.
So you never read/write correct coords if they negative.

I wrote own extensions:
```
public static (double Latitude, double Longitude)? GetGpsCoords(this ImageFile file)
{
    try
    {
        var latitudeRef = file.Properties[ExifTag.GPSLatitudeRef].Value as GPSLatitudeRef?;
        var longitudeRef = file.Properties[ExifTag.GPSLongitudeRef].Value as GPSLongitudeRef?;
        var gpsLatitude = file.Properties[ExifTag.GPSLatitude] as GPSLatitudeLongitude;
        var gpsLongitude = file.Properties[ExifTag.GPSLongitude] as GPSLatitudeLongitude;

        if (latitudeRef is null || longitudeRef is null || gpsLatitude is null || gpsLongitude is null)
            return null;

        var latitude = gpsLatitude.ToFloat() * (latitudeRef.Value is GPSLatitudeRef.North ? 1.0 : -1.0);
        var longitude = gpsLongitude.ToFloat() * (longitudeRef.Value is GPSLongitudeRef.East ? 1.0 : -1.0);

        return (latitude, longitude);
    }
    catch
    {
        return null;
    }
}

public static void SetGpsCoords(this ImageFile file, double latitude, double longitude)
{
    var latitudeRef = latitude >= 0 ? GPSLatitudeRef.North : GPSLatitudeRef.South;
    var longitudeRef = longitude >= 0 ? GPSLongitudeRef.East : GPSLongitudeRef.West;
    
    var objLat = GPSLatitudeLongitude.FromFloat(Math.Abs((float)latitude));
    var objLng = GPSLatitudeLongitude.FromFloat(Math.Abs((float)longitude));
    
    file.Properties.Set(ExifTag.GPSLatitude, objLat.d, objLat.m, objLat.s);
    file.Properties.Set(ExifTag.GPSLongitude, objLng.d, objLng.m, objLng.s);
    file.Properties.Set(ExifTag.GPSLatitudeRef, latitudeRef);
    file.Properties.Set(ExifTag.GPSLongitudeRef, longitudeRef);
}
```

Can you update this in Nuget also?

**Comment by samafshari** [comment]
Thanks! Merged and being released :)
